### ISSUE TITLE
Getting more info off alphaess.com

### ISSUE THREAD

**Issue by tbgoose** [wooni005/alpha-ess-web_mqtt#1]
Hey wooni005, 

I have this installed and running fine. The values are getting pulled from alphaess.com and hitting my mqtt broker. From there I am adding them as sensors in home assistant. 

Just curious if you think it would be possible to either / both get more values from the website (total power used in a day etc), and also alter the output values to make what gets pulled down more accurate. If my load is 750w, then the script reports it as 0.7kw, which obviously isn't true. A lot gets lost in the rounding here, especially at higher numbers. It would be great if I could get the value in watts, and for it to not round to the nearest 100w.

I've had a look at the code and its beyond me how it gets the values it does, but it looks like it  is pulling a value from a graph.

I know you didn't write actual py script that interacts with the website, just curious if you've poked around at all?

Cheers

**Comment by wooni005** [comment]
Hi,
I think it would be possible to get more data from the website, but I don't invest more time in this, because I've the interface running via Modbus. This is real-time data and far more accurate. Also it's tricky with webscraping that if anything changes in the website, you don't receive any data anymore until you solved the issue. Not the way to go on the long term. And I've everything on local. This is the service what I've build myself: https://github.com/wooni005/alpha-ess-modbus_mqtt
And this is what I'm using for getting the grid data: https://github.com/wooni005/acr10r_mqtt
Every second you get an update ;-)
I'm using this all with the Storion T10.
Success,
Arjan

**Comment by tbgoose** [comment]
He Arjan, thanks for the response. Modbus looks promising. I will reach out to alphaess to check if I can set up a similar thing. Already have ethernet running to my storion unit through conduit, so can relatively easily run another cable to my network rack to a pi.

Cheers
